const STRING = {
    welcomeTo: 'Welcome To',
    cAndCHotels: 'C & C Hotels',
    getStarted: 'Get Started',
    login: 'Login',
    forgotPassword: 'Forgot Password ?',
    or: 'Or',
    google: 'Google',
    dontHaveAnAccount: "Don't have an account ?",
    signUp: ' Sign up',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    agreeTo: 'Agree To ',
    terms: 'Terms ',
    conditions: 'Conditions',
    alreadyHaveAnAccount: 'Already have an account ? ',
    emailEnteranceText: "Don’t worry it happens. Please enter the\naddress associated with your account",
    submit: 'Submit',
    enterOtp: 'Enter OTP',
    otpCodeSend: 'An 4 digit code has been sent to johndeo123@gmail.com',
    reset: 'Reset',
    newPassword: 'New Password',
    searchHere: 'Search here...',
    map: 'Map',
    experience: 'Experiences',
    destinations: 'Destinations',
    match: 'Match',
    popularHotel: 'Popular Hotel',
    auraHouse: 'Aura House',
    france: 'France',
    followOurBrands: 'Follow Our Brands',
    villaMia: 'Villa Mia',
    coast: 'Abidjan, Ivory Coast',
    webSite: 'Website',
    factEstablish: 'It is a long established fact that a\nreader will be distracted by the .',
    bookNow: 'Book Now',
    experience: 'Experiences',
    beach: 'Beach',
    village: 'Village',
    cityShopping: 'City & Shopping',
    mountainSky: 'Mountain & Sky',
    nature: 'Nature',
    waterFront: 'Waterfront',
    beachSideHotel: 'Beach Side Hotels',
    villageSideHotel: 'Village Side Hotels',
    letFindYourMatchingHotel: "Let’s Find Your\nMatching Hotels",
    dataFillUp: 'Please fill up the following data to find your\nmatching hotel',
    search: 'Search',
    discover: 'Discover',
    favourite: 'Favourites',
    book: 'Book',
    popularHotel: 'Popular Hotel',
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    settings: 'Settings',
    uploadImage: 'Upload Image',
    name: 'Name :',
    dob: 'DOB :',
    mobileNumber: 'Mobile No :',
    gender: 'Gender :',
    address: 'Address :',
    city: 'City :',
    country: 'Country :',
    postalCode: 'Postal Code :',
    save: 'Save',
    settings: 'Settings',
    language: 'Language',
    subscribe: 'Subscribe',
    howItWorks: 'How it works ?',
    blog: 'Blog',
    rateTheApp: 'Rate the app',
    legalNotice: 'Legal Notice',
    personalData: 'Personal Data',
    aboutDeveloper: 'About Developer',
    logOut: 'Logout',
    doYouWantToLogout: 'Do you want to logout ?',
    yes: 'Yes',
    no: 'No',
    english: 'English',
    french: 'French',
    spanish: 'Spanish',
    selectContinent:'Select Continent',
    selectCountry:'Select Country',
    selectRegion:'Select Region',
    selectDate:'Select Date'

}

export { STRING }