const IMAGES = {
    back_arrow: require('../asset/images/back_arrow.png'),
    ic_email: require('../asset/images/ic_email.png'),
    ic_google: require('../asset/images/ic_google.png'),
    ic_s_password: require('../asset/images/ic_s_password.png'),
    login_img: require('../asset/images/login_img.png'),
    logo: require('../asset/images/logo.png'),
    right_button: require('../asset/images/right_button.png'),
    splash_bg: require('../asset/images/splash_bg.png'),
    login_bg: require('../asset/images/login_bg.png'),
    rectangle: require('../asset/images/rectangle.png'),
    right_bg: require('../asset/images/right_bg.png'),
    forgot_bg: require('../asset/images/forgot_bg.png'),
    otp_bg: require('../asset/images/otp_bg.png'),
    reset_pw_bg: require('../asset/images/reset_pw_bg.png'),
    home_tab: require('../asset/images/home_tab.png'),
    booking_tab: require('../asset/images/booking_tab.png'),
    favourite_tab: require('../asset/images/favourite_tab.png'),
    profile_tab: require('../asset/images/profile_tab.png'),
    ic_eye_password: require('../asset/images/ic_eye_password.png'),
    ic_menu: require('../asset/images/ic_menu.png'),
    ic_down: require('../asset/images/ic_down.png'),
    ic_search: require('../asset/images/ic_search.png'),
    ic_map: require('../asset/images/ic_map.png'),
    ic_expereience: require('../asset/images/ic_expereience.png'),
    ic_destination: require('../asset/images/ic_destination.png'),
    ic_match: require('../asset/images/ic_match.png'),
    ic_forward: require('../asset/images/ic_forward.png'),
    ic_heart: require('../asset/images/ic_heart.png'),
    ic_share: require('../asset/images/ic_share.png'),
    ic_star: require('../asset/images/ic_star.png'),
    cosyplace_bg: require('../asset/images/cosyplace_bg.png'),
    cosylux_bg: require('../asset/images/cosylux_bg.png'),
    generation_bg: require('../asset/images/generation_bg.png'),
    harme_bg: require('../asset/images/harme_bg.png'),
    hotel_bg: require('../asset/images/hotel_bg.png'),
    ic_calender: require('../asset/images/ic_calender.png'),
    ic_heart_white: require('../asset/images/ic_heartwhite.png'),
    profile_bg: require('../asset/images/profile_bg.png'),
    setting_bg: require('../asset/images/setting_bg.png'),
    edit_bg: require('../asset/images/edit_bg.png'),
    image_bg: require('../asset/images/image_bg.png'),
    dashboard_bg: require('../asset/images/dashboard_bg.png'),
    map_bg: require('../asset/images/map_bg.png'),
    carousel_bg: require('../asset/images/carousel_bg.png'),
    map_hotel_bg: require('../asset/images/map_hotel_bg.png'),
    hoteldetail_bg: require('../asset/images/hoteldetail_bg.png'),
    asia_bg: require('../asset/images/asia_bg.png'),
    europe_bg: require('../asset/images/europe_bg.png'),
    northamerica_bg: require('../asset/images/northamerica_bg.png'),
    southamerica_bg: require('../asset/images/southamerica_bg.png'),
    africa_bg: require('../asset/images/africa_bg.png'),
    popularhotel_bg: require('../asset/images/popularhotel_bg.png'),
    ic_profile: require('../asset/images/ic_profile.png'),
    ic_heart_white:require('../asset/images/ic_heart_white.png')

}

export { IMAGES }